[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-cross/bin/aarch64-linux-musl-ld"

[env]
CC_aarch64-unknown-linux-musl = "/home/shinydemon/Documents/asyncembedded2022/aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"